const cardData = [
    {
        pair: "BTC/USD",
        timeline: "SPOT · 5 мин. назад",
        profitTitle: "Прибыль",
        profitPercentage: "45.89%",
        target: "Цель 1",
        entryDate: "Дата входа 15.02.2025",
    },
    {
        pair: "ETH/USD",
        timeline: "FUTURES · 10 мин. назад",
        profitTitle: "Прибыль",
        profitPercentage: "32.54%",
        target: "Цель 2",
        entryDate: "Дата входа 14.02.2025",
    },
    {
        pair: "NEAR/USD",
        timeline: "SPOT · 1 час назад",
        profitTitle: "Прибыль",
        profitPercentage: "58.62%",
        target: "Цель 4",
        entryDate: "Дата входа 13.02.2025",
    },
    {
        pair: "BTC/USD",
        timeline: "FUTURES · 3 мин. назад",
        profitTitle: "Прибыль",
        profitPercentage: "25.74%",
        target: "Цель 3",
        entryDate: "Дата входа 12.02.2025",
    },
    {
        pair: "ETH/USD",
        timeline: "SPOT · 15 мин. назад",
        profitTitle: "Прибыль",
        profitPercentage: "49.11%",
        target: "Цель 5",
        entryDate: "Дата входа 11.02.2025",
    },
    {
        pair: "NEAR/USD",
        timeline: "FUTURES · 30 мин. назад",
        profitTitle: "Прибыль",
        profitPercentage: "61.47%",
        target: "Цель 6",
        entryDate: "Дата входа 10.02.2025",
    },
    {
        pair: "BTC/USD",
        timeline: "SPOT · 2 часа назад",
        profitTitle: "Прибыль",
        profitPercentage: "33.33%",
        target: "Цель 7",
        entryDate: "Дата входа 09.02.2025",
    },
    {
        pair: "ETH/USD",
        timeline: "FUTURES · 5 часов назад",
        profitTitle: "Прибыль",
        profitPercentage: "28.95%",
        target: "Цель 8",
        entryDate: "Дата входа 08.02.2025",
    },
    {
        pair: "NEAR/USD",
        timeline: "SPOT · 10 часов назад",
        profitTitle: "Прибыль",
        profitPercentage: "54.78%",
        target: "Цель 9",
        entryDate: "Дата входа 07.02.2025",
    },
];
export { cardData };
